import type { Metadata } from "next";
import "./globals.css";
import { feta, poppins } from "./fonts";
import { Footer, Header } from "@/components";
import { QueryProvider } from "@/lib/QueryProvider";

export const metadata: Metadata = {
  title: "Alice A.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={`${poppins.variable} ${feta.className} `}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </QueryProvider>
  );
}
